var searchData=
[
  ['callbackslot_0',['CallbackSlot',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28_29_3e_1',['CallbackSlot&lt; void()&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20double_20stamp_2c_20const_20eigen_3a_3avector3d_20_26linear_5facc_2c_20const_20eigen_3a_3avector3d_20_26angular_5fvel_29_3e_2',['CallbackSlot&lt; void(const double stamp, const Eigen::Vector3d &amp;linear_acc, const Eigen::Vector3d &amp;angular_vel)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20estimationframe_3a_3aconstptr_20_26estimated_5fframe_29_3e_3',['CallbackSlot&lt; void(const EstimationFrame::ConstPtr &amp;estimated_frame)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20estimationframe_3a_3aconstptr_20_26frame_29_3e_4',['CallbackSlot&lt; void(const EstimationFrame::ConstPtr &amp;frame)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20gtsam_5fpoints_3a_3alevenbergmarquardtoptimizationstatus_20_26status_2c_20const_20gtsam_3a_3avalues_20_26values_29_3e_5',['CallbackSlot&lt; void(const gtsam_points::LevenbergMarquardtOptimizationStatus &amp;status, const gtsam::Values &amp;values)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20preprocessedframe_3a_3aconstptr_20_26points_2c_20const_20eigen_3a_3aisometry3d_20_26t_5fodom_5flidar_29_3e_6',['CallbackSlot&lt; void(const PreprocessedFrame::ConstPtr &amp;points, const Eigen::Isometry3d &amp;T_odom_lidar)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20preprocessedframe_3a_3aptr_20_26frame_29_3e_7',['CallbackSlot&lt; void(const PreprocessedFrame::Ptr &amp;frame)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20rawpoints_3a_3aconstptr_20_26points_29_3e_8',['CallbackSlot&lt; void(const RawPoints::ConstPtr &amp;points)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20std_3a_3avector_3c_20estimationframe_3a_3aconstptr_20_3e_20_26frames_29_3e_9',['CallbackSlot&lt; void(const std::vector&lt; EstimationFrame::ConstPtr &gt; &amp;frames)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20std_3a_3avector_3c_20estimationframe_3a_3aconstptr_20_3e_20_26keyframes_29_3e_10',['CallbackSlot&lt; void(const std::vector&lt; EstimationFrame::ConstPtr &gt; &amp;keyframes)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20std_3a_3avector_3c_20estimationframe_3a_3aconstptr_20_3e_20_26marginalized_5fframes_29_3e_11',['CallbackSlot&lt; void(const std::vector&lt; EstimationFrame::ConstPtr &gt; &amp;marginalized_frames)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20std_3a_3avector_3c_20estimationframe_3a_3aconstptr_20_3e_20_26marginalized_5fkeyframes_29_3e_12',['CallbackSlot&lt; void(const std::vector&lt; EstimationFrame::ConstPtr &gt; &amp;marginalized_keyframes)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20std_3a_3avector_3c_20submap_3a_3aptr_20_3e_20_26submaps_29_3e_13',['CallbackSlot&lt; void(const std::vector&lt; SubMap::Ptr &gt; &amp;submaps)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28const_20submap_3a_3aconstptr_20_26submap_29_3e_14',['CallbackSlot&lt; void(const SubMap::ConstPtr &amp;submap)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28double_29_3e_15',['CallbackSlot&lt; void(double)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28gtsam_3a_3anonlinearfactorgraph_20_26graph_2c_20gtsam_3a_3avalues_20_26values_29_3e_16',['CallbackSlot&lt; void(gtsam::NonlinearFactorGraph &amp;graph, gtsam::Values &amp;values)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28gtsam_5fpoints_3a_3aincrementalfixedlagsmootherextwithfallback_20_26smoother_29_3e_17',['CallbackSlot&lt; void(gtsam_points::IncrementalFixedLagSmootherExtWithFallback &amp;smoother)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28gtsam_5fpoints_3a_3aincrementalfixedlagsmootherextwithfallback_20_26smoother_2c_20gtsam_3a_3anonlinearfactorgraph_20_26new_5ffactors_2c_20gtsam_3a_3avalues_20_26new_5fvalues_2c_20std_3a_3amap_3c_20std_3a_3auint64_5ft_2c_20double_20_3e_20_26new_5fstamps_29_3e_18',['CallbackSlot&lt; void(gtsam_points::IncrementalFixedLagSmootherExtWithFallback &amp;smoother, gtsam::NonlinearFactorGraph &amp;new_factors, gtsam::Values &amp;new_values, std::map&lt; std::uint64_t, double &gt; &amp;new_stamps)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28gtsam_5fpoints_3a_3aisam2ext_20_26isam2_2c_20const_20gtsam_5fpoints_3a_3aisam2resultext_20_26result_29_3e_19',['CallbackSlot&lt; void(gtsam_points::ISAM2Ext &amp;isam2, const gtsam_points::ISAM2ResultExt &amp;result)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28gtsam_5fpoints_3a_3aisam2ext_20_26isam2_2c_20gtsam_3a_3anonlinearfactorgraph_20_26new_5ffactors_2c_20gtsam_3a_3avalues_20_26new_5fvalues_29_3e_20',['CallbackSlot&lt; void(gtsam_points::ISAM2Ext &amp;isam2, gtsam::NonlinearFactorGraph &amp;new_factors, gtsam::Values &amp;new_values)&gt;',['../classCallbackSlot.html',1,'']]],
  ['callbackslot_3c_20void_28int_20id_2c_20const_20estimationframe_3a_3aconstptr_20_26keyframe_29_3e_21',['CallbackSlot&lt; void(int id, const EstimationFrame::ConstPtr &amp;keyframe)&gt;',['../classCallbackSlot.html',1,'']]],
  ['cloudcovarianceestimation_22',['CloudCovarianceEstimation',['../classglim_1_1CloudCovarianceEstimation.html',1,'glim']]],
  ['clouddeskewing_23',['CloudDeskewing',['../classglim_1_1CloudDeskewing.html',1,'glim']]],
  ['cloudpreprocessor_24',['CloudPreprocessor',['../classglim_1_1CloudPreprocessor.html',1,'glim']]],
  ['cloudpreprocessorparams_25',['CloudPreprocessorParams',['../structglim_1_1CloudPreprocessorParams.html',1,'glim']]],
  ['concurrentvector_26',['ConcurrentVector',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['concurrentvector_3c_20boost_3a_3ashared_5fptr_3c_20gtsam_3a_3anonlinearfactor_20_3e_20_3e_27',['ConcurrentVector&lt; boost::shared_ptr&lt; gtsam::NonlinearFactor &gt; &gt;',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['concurrentvector_3c_20eigen_3a_3amatrix_3c_20double_2c_207_2c_201_20_3e_20_3e_28',['ConcurrentVector&lt; Eigen::Matrix&lt; double, 7, 1 &gt; &gt;',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['concurrentvector_3c_20estimationframe_3a_3aconstptr_20_3e_29',['ConcurrentVector&lt; EstimationFrame::ConstPtr &gt;',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['concurrentvector_3c_20glim_3a_3aloopcandidate_20_3e_30',['ConcurrentVector&lt; glim::LoopCandidate &gt;',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['concurrentvector_3c_20preprocessedframe_3a_3aptr_20_3e_31',['ConcurrentVector&lt; PreprocessedFrame::Ptr &gt;',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['concurrentvector_3c_20submap_3a_3aptr_20_3e_32',['ConcurrentVector&lt; SubMap::Ptr &gt;',['../classglim_1_1ConcurrentVector.html',1,'glim']]],
  ['config_33',['Config',['../classglim_1_1Config.html',1,'glim']]]
];
